[program:reverb]
process_name=%(program_name)s
command=php /var/www/collabee/artisan reverb:start
autostart=true
autorestart=true
user=forge
redirect_stderr=true
stdout_logfile=/var/www/collabee/storage/logs/reverb.log
